#!/usr/bin/env python3
"""
generate_digest.py — builds _digest.md from all entity snapshot frontmatter.

Reads every entity snapshot (type: snapshot in frontmatter), extracts
the key orientation fields, and writes a single compressed file at the root.
One read replaces N snapshot reads at session open.

Usage:
    python scripts/generate_digest.py
"""

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
DIGEST_PATH = ROOT / "_digest.md"
ENTITIES_DIR = ROOT / "entities"


def parse_frontmatter(content: str) -> dict:
    match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    if not match:
        return {}

    fm: dict = {}
    lines = match.group(1).splitlines()
    current_key = None
    current_list: list[str] = []

    for line in lines:
        # List item under current key
        if re.match(r"^\s{2,}- ", line):
            val = re.sub(r'^\s*-\s*"?|"?\s*$', "", line).strip().strip('"')
            if val:
                current_list.append(val)
            continue

        # New key: value line
        m = re.match(r'^(\w[\w_]*):\s*(.*)', line)
        if m:
            # Flush previous list
            if current_key and current_list:
                fm[current_key] = current_list
                current_list = []
            key = m.group(1)
            value = m.group(2).strip().strip('"')
            if value:
                fm[key] = value
            current_key = key
        else:
            # Continuation of a quoted block (e.g. multi-line current_state)
            if current_key and current_key in fm and isinstance(fm[current_key], str):
                fm[current_key] += " " + line.strip().strip('"')

    if current_key and current_list:
        fm[current_key] = current_list

    return fm


def format_bullets(items) -> str:
    if not items:
        return "  —"
    if isinstance(items, str):
        return f"  - {items}"
    return "\n".join(f"  - {item}" for item in items)


def run():
    snapshots = []
    for path in sorted(ENTITIES_DIR.rglob("*.md")):
        if path.name.startswith("_"):
            continue
        content = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(content)
        if fm.get("type") != "snapshot":
            continue
        snapshots.append((fm.get("entity", path.stem), fm, path))

    if not snapshots:
        print("No entity snapshots found.")
        return

    today = date.today().isoformat()
    blocks = [
        f"---\ntype: digest\ngenerated: {today}\n---\n",
        f"# Context Digest — {today}\n",
        "_Generated by `scripts/generate_digest.py`. Refresh after /wrap._\n",
        "_Read this instead of opening individual snapshots at session start._\n",
    ]

    for name, fm, path in sorted(snapshots, key=lambda x: x[0]):
        rel = path.relative_to(ROOT)
        blocks.append(f"---\n\n## {name}  ·  `{rel}`")
        blocks.append(f"_Last updated: {fm.get('last_updated', '?')}_\n")

        state = fm.get("current_state", "")
        if state:
            blocks.append(f"**State:** {state}\n")

        focus = fm.get("current_focus", [])
        if focus:
            blocks.append("**Current Focus:**")
            blocks.append(format_bullets(focus))
            blocks.append("")

        next_actions = fm.get("next_actions", [])
        if next_actions:
            blocks.append("**Next Actions:**")
            blocks.append(format_bullets(next_actions))
            blocks.append("")

        tensions = fm.get("tensions", [])
        if tensions:
            blocks.append("**Tensions:**")
            blocks.append(format_bullets(tensions))
            blocks.append("")

    output = "\n".join(blocks)
    DIGEST_PATH.write_text(output, encoding="utf-8")
    print(f"_digest.md written ({len(snapshots)} entities, {len(output)} chars)")


if __name__ == "__main__":
    run()
